### ISSUE TITLE
Minor Fixes

### ISSUE THREAD

**Issue by ppap1771** [IIITKalyaniFOSC/Hackathon-website-2023#17]
- [ ]  Read CONTRIBUTING.md.
- [ ] Change the width of the landing page text to incorporate the white space. 
- [ ] Left-hand side margin fix to have equal margins on both ends.
- [ ] Fix alignment issues in the RULES and FAQ section.
- [ ]  Change the social media icons and add greyscale ones.
- [ ] Add animations to major headings like the `$ man status_code_0`.
- [ ] Make sure the changes work well keeping in mind the responsiveness of the website.

**Comment by bhaskar1001101** [comment]
Please assign me this issue @ppap1771.
