### ISSUE TITLE
Create a Team section for the website.

### ISSUE THREAD

**Issue by ppap1771** [IIITKalyaniFOSC/Hackathon-website-2023#20]
- [ ] Read CONTRIBUTING.md
- [ ] Ask to be assigned to the issue 
- [ ] Come up with a design for the page or get it designed by the design team.
- [ ] Implement the design
- [ ] Make a PR with your changes to address this issue.

**Comment by TeeWrath** [comment]
Assign me this issue @ppap1771 pls
